### ISSUE TITLE
[feat] 모니터링

### ISSUE THREAD

**Issue by chrisheo** [Kakao-X-Goorm-DEEP-DIVE-course/voting_system#6]
### 💼 작업 설명
5. 모니터링
Prometheus 및 Grafana 등을 이용하여 시스템 성능 및 서비스 상태 모니터링
로그 및 메트릭 수집을 통한 장애 감지 시스템 구현

### ✅ To-do

- [ ] Prometheus, Grafana init
- [ ] api와 모니터링 연동
- [ ] 메트릭 조건 설정 및 알림 구현
